apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # Doit correspondre aux labels de votre Deployment
  ports:
    - protocol: TCP
      port: 80  # Port exposé par le service
      targetPort: 3000  # Port sur lequel vos pods backend écoutent